language: python
python:
    - "3.2_with_system_site_packages"
before_install:
    - "sudo apt-get update"
install:
    - "sudo apt-get install -y python3-pyside"
script:
    - "python -m unittest discover -s src/tests/ -t src"