language: python
python:
    - "3.2_with_system_site_packages"
    - "3.3"
before_install:
    - "sudo apt-get update"
install:
    - pip install -U PySide
    - pip install coveralls pylama
script:
    - pylama src/
    - xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x16" coverage run --source=src -m unittest discover -s src/tests/ -t src
after_success:
    coveralls

